name: nextjs
icon: nextjs
title: Next.js

services:
- name: nextjs
  title: Next.js
  service: nextjs
  required: true
  links:
  - name: db
    service: postgres
  - name: redis
    service: valkey
  - name: sendmail
    service: mailpit

- name: postgres
  disabled: true
  title: PostgreSQL
  required: false
  service: postgres
  volumes:
  - name: data
    size: 10   

- name: valkey
  disabled: true
  title: Valkey
  service: valkey

- name: mailpit
  disabled: true
  title: Mailpit
  service: mailpit

- name: opensmtpd
  disabled: true
  title: OpenSMTPD
  service: opensmtpd

- name: gotenberg
  required: false
  disabled: true
  title: Gotenberg
  service: gotenberg
